# Generated by Django 5.0 on 2023-12-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='training',
            field=models.ManyToManyField(to='web.training'),
        ),
    ]
